### ISSUE TITLE
Callback for bullet shoot

### ISSUE THREAD

**Issue by dasheck0** [16patsle/phaser3-weapon-plugin#17]
Thank you for the port of this plugin. I used it for a game lately. I did not find a way to add a callback for when a bullet is shot / started, so that you can add a sound. Would be amazing to have this!

**Comment by 16patsle** [comment]
Hey @dasheck0, sorry for taking a (long) while to answer. The Weapon emits a fire event, which you can listen to using almost the same syntax as other Phaser events.

```javascript
this.weapon.eventEmitter.on('fire', fireCallback);
```

There are a few other events too (like fireLimit and kill), but they're not too well documented right now. I'll see if I can get them better documented and available via the `weapon.on` syntax instead of `weapon.eventEmitter.on` in the next release.

**Comment by 16patsle** [comment]
I've also added an example using this, the `on-fire` example
